name: Ruby #Githubリポジトリの[Actions]タブに表示されるワークフローの名前

on: [push] # ワークフローを自動的にトリガーするイベント

jobs:  # このファイルで実行されるジョブをグループ化(仮想環境の新しいインスタンスで実行される)
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest #ジョブを実行する仮想マシン
    
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:  #ジョブが実行する処理の集合
    - uses: actions/checkout@v1
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.3
    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --path vendor/bundle --without production
        yarn install

    - name: Set env
      env:
        RAILS_ENV: test
    - name: setup DB
      run: |
        bundle exec rails db:schema:load

    - name: Run RSpec
      run: |
        bundle exec rspec