name: Ruby #Githubリポジトリの[Actions]タブに表示されるワークフローの名前

on: [push] # ワークフローを自動的にトリガーするイベント #デフォでmasterになってる？

jobs:  # このファイルで実行されるジョブをグループ化(仮想環境の新しいインスタンスで実行される)
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest #ジョブを実行する仮想マシン

    steps:  #ジョブが実行する処理の集合
    - uses: actions/checkout@v1  #チェックアウト？
    - name: Setup up Ruby 2.6
      uses: actions/setup-ruby@v1 #rubyの実行環境をインストール？
      with:
        ruby-version: 2.6.3
    - name: Run RSpec
      run: |
        gem install bundler
        bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
        bundle exec rspec