name: Ruby #Githubリポジトリの[Actions]タブに表示されるワークフローの名前

on: [push] # ワークフローを自動的にトリガーするイベント

jobs:  # このファイルで実行されるジョブをグループ化(仮想環境の新しいインスタンスで実行される)
  run_spec:
    name: Run spec
    runs-on: ubuntu-latest #ジョブを実行する仮想マシン
    
    services:
      postgres:
        image: postgres:12
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: password
          POSTGRES_DATABASE: Life-changing_test

    container:
      image: ruby:2.6.3
      env:
        RAILS_ENV: test

    steps:  #ジョブが実行する処理の集合
    - name: checkout
      uses: actions/checkout@v2
    - name: update library
      run: |
        apt-get update
    - name: install node
      run: |
        curl -sL https://deb.nodesource.com/setup_12.x | bash -
        apt-get install -y nodejs
    - name: install yarn
      run: |
        curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
        echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
        apt-get update
        apt-get install -y yarn
    - name: Prepare bundler
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
    - name: Prepare database
      run: |
        cp config/database.github-actions.yml config/database.yml
        bundle exec rails db:test:prepare
    - name: Run RSpec
      run: |
        run: TZ=Asiz/Tokyo bundle exec rspec -f d